/**
 * Authentication Schema (Better Auth tables)
 *
 * Tables required by Better Auth for user authentication.
 * Using PostgreSQL with Drizzle ORM.
 */

import { pgTable, text, timestamp, boolean, index } from "drizzle-orm/pg-core";

// =============================================================================
// User Table
// =============================================================================
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  
  // Role and admin fields
  role: text("role").notNull().default("user"),
  
  // Ban status
  banned: boolean("banned").notNull().default(false),
  bannedReason: text("banned_reason"),
  bannedAt: timestamp("banned_at"),
  
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// =============================================================================
// Type Exports
// =============================================================================
export type User = typeof user.$inferSelect;
export type InsertUser = typeof user.$inferInsert;
export type UserRole = "user" | "admin";

// =============================================================================
// Session Table
// =============================================================================
export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_user_id_idx").on(table.userId)]
);

// =============================================================================
// Account Table (OAuth providers)
// =============================================================================
export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("account_user_id_idx").on(table.userId),
    index("account_provider_id_idx").on(table.providerId, table.accountId),
  ]
);

// =============================================================================
// Verification Table (email verification, password reset)
// =============================================================================
export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
);

/**
 * Better Auth's `jwks` table — the signing keys behind /api/auth/token and the
 * public set served at /api/auth/jwks
 * (charter decisions/2026-08-15-one-issuer-and-offline-verification.md).
 *
 * Declared here rather than generated by the Better Auth CLI because this hub's
 * schema is Drizzle-owned and its migrations apply on boot. The plugin was wired
 * up with no table behind it, which typechecks and passes every unit test and
 * then 500s the first time anyone asks for a token — the same shape of defect as
 * a capability advertised because a binary resolved.
 *
 * Column names are Better Auth's, camelCase and quoted, because the plugin's
 * adapter reads them by those names — `publicKey`, not `public_key`. That is the
 * one place in this schema where the house style does not apply, and changing it
 * to match would break the plugin at runtime while looking tidier.
 *
 * ROTATION lives in this table's shape, and it is worth knowing before an
 * incident: `/api/auth/jwks` publishes EVERY row, and signing uses the row with
 * the newest `createdAt` (better-auth plugins/jwt/adapter.mjs — getAllKeys and
 * getLatestKey). So an overlapping rotation is: insert a newer key, let old
 * tokens drain, then delete the old row. #331 measured the sharp edge — a
 * retired key keeps verifying at a consumer until that consumer's JWKS cache
 * expires, so deleting a row is NOT an emergency revocation lever.
 */
export const jwks = pgTable("jwks", {
  id: text("id").primaryKey(),
  publicKey: text("publicKey").notNull(),
  privateKey: text("privateKey").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  expiresAt: timestamp("expiresAt"),
});
