package skills

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"
)

// The checked-in synthetic fixture is generated by Python with the library's
// json_bytes/pack conventions. It contains no private skill content.
func fixtureArchive(t *testing.T) ([]byte, string, string) {
	t.Helper()
	data, err := os.ReadFile("testdata/export-codex.tar.gz")
	if err != nil {
		t.Fatal(err)
	}
	metadata, err := os.ReadFile("testdata/exports.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixtures []struct{ Harness, ArchiveSHA256, BundleDigest string }
	if err := json.Unmarshal(metadata, &fixtures); err != nil {
		t.Fatal(err)
	}
	for _, fixture := range fixtures {
		if fixture.Harness == "codex" {
			return data, fixture.ArchiveSHA256, fixture.BundleDigest
		}
	}
	t.Fatal("missing Codex fixture metadata")
	return nil, "", ""
}

func TestArtifactAcceptsLibraryArchive(t *testing.T) {
	data, archiveHash, bundleHash := fixtureArchive(t)
	artifact, err := ReadArtifact(context.Background(), bytes.NewReader(data), archiveHash, "codex")
	if err != nil {
		t.Fatal(err)
	}
	if artifact.Manifest.Digest != bundleHash || artifact.ArchiveSHA256 != archiveHash || artifact.Manifest.Name != "sjl-fixture" {
		t.Fatalf("incorrect identity: %+v", artifact)
	}
	if len(artifact.Files) < 5 || !bytes.Contains(artifact.Files["skills/sjl-fixture/SKILL.md"], []byte("synthetic bundle")) {
		t.Fatal("missing verified files")
	}
}

func rewriteArchive(t *testing.T, original []byte, edit func(*tar.Header, []byte) (*tar.Header, []byte)) []byte {
	t.Helper()
	gz, err := gzip.NewReader(bytes.NewReader(original))
	if err != nil {
		t.Fatal(err)
	}
	defer gz.Close()
	r := tar.NewReader(gz)
	var output bytes.Buffer
	z := gzip.NewWriter(&output)
	w := tar.NewWriter(z)
	for {
		h, err := r.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		data, err := io.ReadAll(r)
		if err != nil {
			t.Fatal(err)
		}
		h, data = edit(h, data)
		if h == nil {
			continue
		}
		h.Size = int64(len(data))
		if err := w.WriteHeader(h); err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write(data); err != nil {
			t.Fatal(err)
		}
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	if err := z.Close(); err != nil {
		t.Fatal(err)
	}
	return output.Bytes()
}

func TestArtifactRejectsUntrustedArchive(t *testing.T) {
	original, pin, _ := fixtureArchive(t)
	for name, edit := range map[string]func(*tar.Header, []byte) (*tar.Header, []byte){
		"traversal": func(h *tar.Header, b []byte) (*tar.Header, []byte) { h.Name = "sjl-fixture/../escape"; return h, b },
		"absolute":  func(h *tar.Header, b []byte) (*tar.Header, []byte) { h.Name = "/escape"; return h, b },
		"backslash": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			h.Name = "sjl-fixture/skills\\escape"
			return h, b
		},
		"link": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			h.Typeflag = tar.TypeSymlink
			h.Linkname = "outside"
			return h, nil
		},
		"special": func(h *tar.Header, b []byte) (*tar.Header, []byte) { h.Typeflag = tar.TypeFifo; return h, nil },
		"case collision": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			h.Name = "sjl-fixture/SKILLS/fixture/SKILL.md"
			return h, b
		},
		"edited content": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			if h.Name == "sjl-fixture/skills/sjl-fixture/SKILL.md" {
				b = append(b, 'x')
			}
			return h, b
		},
		"changed executable bit": func(h *tar.Header, b []byte) (*tar.Header, []byte) { h.Mode = 0755; return h, b },
		"missing manifest": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			if h.Name == "sjl-fixture/sjl-bundle.json" {
				return nil, nil
			}
			return h, b
		},
		"duplicate JSON key": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			if h.Name == "sjl-fixture/sjl-bundle.json" {
				b = bytes.Replace(b, []byte("{\n"), []byte("{\n  \"name\": \"sjl-other\",\n"), 1)
			}
			return h, b
		},
		"false manifest digest": func(h *tar.Header, b []byte) (*tar.Header, []byte) {
			if h.Name == "sjl-fixture/sjl-bundle.json" {
				b = bytes.Replace(b, []byte("0.1.0"), []byte("0.2.0"), 1)
			}
			return h, b
		},
	} {
		t.Run(name, func(t *testing.T) {
			data := rewriteArchive(t, original, edit)
			hash := fmt.Sprintf("%x", sha256.Sum256(data))
			if _, err := ReadArtifact(context.Background(), bytes.NewReader(data), hash, "codex"); err == nil {
				t.Fatal("accepted invalid artifact")
			}
		})
	}
	if _, err := ReadArtifact(context.Background(), bytes.NewReader(original), pin, "pi"); err == nil {
		t.Fatal("cross-harness artifact accepted")
	}
	if _, err := ReadArtifact(context.Background(), bytes.NewReader(append(original, 'x')), pin, "codex"); err == nil {
		t.Fatal("changed archive accepted")
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := ReadArtifact(ctx, bytes.NewReader(original), pin, "codex"); err == nil {
		t.Fatal("cancelled read accepted")
	}
}

func TestArtifactBounds(t *testing.T) {
	data, _, _ := fixtureArchive(t)
	data = rewriteArchive(t, data, func(h *tar.Header, b []byte) (*tar.Header, []byte) { return h, bytes.Repeat([]byte("x"), (8<<20)+1) })
	if _, err := ReadArtifact(context.Background(), bytes.NewReader(data), fmt.Sprintf("%x", sha256.Sum256(data)), "codex"); err == nil {
		t.Fatal("oversized expansion accepted")
	}
}

func TestArtifactLibraryExporters(t *testing.T) {
	data, err := os.ReadFile("testdata/exports.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixtures []struct{ File, Harness, ArchiveSHA256, BundleDigest string }
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatal(err)
	}
	if len(fixtures) != 6 {
		t.Fatal("expected all six exporter formats")
	}
	for _, fixture := range fixtures {
		t.Run(fixture.Harness, func(t *testing.T) {
			data, err := os.ReadFile("testdata/" + fixture.File)
			if err != nil {
				t.Fatal(err)
			}
			artifact, err := ReadArtifact(context.Background(), bytes.NewReader(data), fixture.ArchiveSHA256, fixture.Harness)
			if err != nil {
				t.Fatal(err)
			}
			if artifact.Manifest.Digest != fixture.BundleDigest {
				t.Fatal("manifest digest differs from Python exporter")
			}
		})
	}
}

func TestArtifactPathCollisions(t *testing.T) {
	for _, paths := range [][]string{{"folder/file", "FOLDER/other"}, {"folder/file", "folder"}, {"folder", "folder/file"}, {"file", "file"}} {
		seen := map[string]archivePathEntry{}
		if err := recordArchivePath(seen, paths[0]); err != nil {
			t.Fatal(err)
		}
		if err := recordArchivePath(seen, paths[1]); err == nil {
			t.Fatalf("accepted colliding paths %q", paths)
		}
	}
}

func TestArtifactRejectsArchiveTails(t *testing.T) {
	data, _, _ := fixtureArchive(t)
	for name, suffix := range map[string][]byte{"garbage": []byte("tail"), "concatenated gzip": data} {
		t.Run(name, func(t *testing.T) {
			joined := append(append([]byte{}, data...), suffix...)
			pin := fmt.Sprintf("%x", sha256.Sum256(joined))
			if _, err := ReadArtifact(context.Background(), bytes.NewReader(joined), pin, "codex"); err == nil {
				t.Fatal("accepted trailing data despite valid archive pin")
			}
		})
	}
	corrupt := append([]byte{}, data...)
	corrupt[len(corrupt)-8] ^= 1
	if _, err := ReadArtifact(context.Background(), bytes.NewReader(corrupt), fmt.Sprintf("%x", sha256.Sum256(corrupt)), "codex"); err == nil {
		t.Fatal("ignored gzip checksum failure")
	}
}

type zeroReader struct{}

func (zeroReader) Read(p []byte) (int, error) { clear(p); return len(p), nil }

func TestArtifactRejectsTransportAndExpansionBounds(t *testing.T) {
	_, err := ReadArtifact(context.Background(), io.LimitReader(zeroReader{}, maxArchiveBytes+1), strings.Repeat("a", 64), "codex")
	if err == nil || !strings.Contains(err.Error(), "compressed artifact exceeds limit") {
		t.Fatalf("compressed input bound: %v", err)
	}
	for _, count := range []int{9, maxArtifactFiles + 1} {
		t.Run(fmt.Sprint(count), func(t *testing.T) {
			var output bytes.Buffer
			gz := gzip.NewWriter(&output)
			writer := tar.NewWriter(gz)
			size := int64(0)
			if count == 9 {
				size = maxArtifactFileBytes
			}
			for i := 0; i < count; i++ {
				header := &tar.Header{Name: fmt.Sprintf("sjl-fixture/file-%04d", i), Mode: 0644, Size: size, Typeflag: tar.TypeReg}
				if err := writer.WriteHeader(header); err != nil {
					t.Fatal(err)
				}
				if _, err := io.CopyN(writer, zeroReader{}, size); err != nil {
					t.Fatal(err)
				}
			}
			if err := writer.Close(); err != nil {
				t.Fatal(err)
			}
			if err := gz.Close(); err != nil {
				t.Fatal(err)
			}
			_, err := ReadArtifact(context.Background(), bytes.NewReader(output.Bytes()), fmt.Sprintf("%x", sha256.Sum256(output.Bytes())), "codex")
			if err == nil {
				t.Fatal("accepted oversized artifact")
			}
			if strings.Contains(err.Error(), "manifest") {
				t.Fatalf("bounds were not enforced before parsing: %v", err)
			}
		})
	}
}

func TestArtifactRejectsFilesystemIncompatiblePaths(t *testing.T) {
	for _, value := range []string{strings.Repeat("a/", 65) + "file", "a/" + strings.Repeat("x", 256), "../escape", "/absolute", "a/./b", "a//b", "a/../b", "café/file", "a/line\nbreak"} {
		if artifactPath(value) {
			t.Fatalf("unsafe or nonportable path accepted: %q", value)
		}
	}
}

func TestArtifactBoundsImplicitDirectories(t *testing.T) {
	seen := map[string]archivePathEntry{}
	for i := 0; i < maxArtifactFiles; i++ {
		name := fmt.Sprintf("tree-%d/", i) + strings.Repeat("a/", 62) + "file"
		if err := recordArchivePath(seen, name); err != nil {
			return
		}
	}
	t.Fatal("implicit directory count was unbounded")
}
